In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
hnews = pd.read_csv('hacker_news.csv')

In [4]:
hnews.head()

,id,title,url,num_points,num_comments,author,created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14

In [7]:
hnews[1:]

,id,title,url,num_points,num_comments,author,created_at
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14
5,12578975,Saving the Hassle of Shopping,https://blog.menswr.com/2016/09/07/whats-new-w...,1,1,bdoux,9/26/2016 3:13
...,...,...,...,...,...,...,...
293114,10176919,Ask HN: What is/are your favorite quote(s)?,NaN,15,20,kumarski,9/6/2015 6:02
293115,10176917,Attention and awareness in stage magic: turnin...,http://people.cs.uchicago.edu/~luitien/nrn2473...,14,0,stakent,9/6/2015 6:01
293116,10176908,Dying vets fuck you letter (2013),http://dangerousminds.net/comments/dying_vets_...,10,2,mycodebreaks,9/6/2015 5:56
293117,10176907,"PHP 7 Coolest Features: Space Ships, Type Hint...",https://www.zend.com/en/resources/php-7,2,0,Garbage,9/6/2015 5:55
293118,10176903,Toyota Establishes Research Centers with MIT a...,http://newsroom.toyota.co.jp/en/detail/9233109/,4,0,tim_sw,9/6/2015 5:50

In [8]:
ask_posts = hnews[hnews['title'].str.contains('Ask HN',case=False)]
show_posts = hnews[hnews['title'].str.contains('Show HN',case=False)]
other_posts = hnews[~hnews['title'].str.contains('Ask HN|Show_HN',case=False,na=False)]

In [9]:
ask_posts

,id,title,url,num_points,num_comments,author,created_at
10,12578908,Ask HN: What TLD do you use for local developm...,NaN,4,7,Sevrene,9/26/2016 2:53
42,12578522,Ask HN: How do you pass on your work when you ...,NaN,6,3,PascLeRasc,9/26/2016 1:17
76,12577908,Ask HN: How a DNS problem can be limited to a ...,NaN,1,0,kuon,9/25/2016 22:57
80,12577870,Ask HN: Why join a fund when you can be an angel?,NaN,1,3,anthony_james,9/25/2016 22:48
102,12577647,Ask HN: Someone uses stock trading as passive ...,NaN,5,2,00taffe,9/25/2016 21:50
...,...,...,...,...,...,...,...
293047,10177359,Ask HN: Is coursera specialization in product ...,NaN,1,0,pipipzz,9/6/2015 11:27
293052,10177317,Ask HN: Any meteor devs out there who could sp...,NaN,2,1,louisswiss,9/6/2015 10:52
293055,10177309,Ask HN: Any recommendations for books about ra...,NaN,2,4,rationalthrowa,9/6/2015 10:46
293073,10177200,Ask HN: Where do you look for work if you need...,NaN,14,20,coroutines,9/6/2015 9:36
293114,10176919,Ask HN: What is/are your favorite quote(s)?,NaN,15,20,kumarski,9/6/2015 6:02

In [10]:
show_posts

,id,title,url,num_points,num_comments,author,created_at
52,12578335,Show HN: Finding puns computationally,http://puns.samueltaylor.org/,2,0,saamm,9/26/2016 0:36
58,12578182,Show HN: A simple library for complicated anim...,https://christinecha.github.io/choreographer-js/,1,0,christinecha,9/26/2016 0:01
64,12578098,Show HN: WebGL visualization of DNA sequences,http://grondilu.github.io/dna.html,1,0,grondilu,9/25/2016 23:44
70,12577991,"Show HN: Pomodoro-centric, heirarchical projec...",https://github.com/jakebian/zeal,2,0,dbranes,9/25/2016 23:17
140,12577142,Show HN: Jumble Essays on the go #PaulInYourP...,https://itunes.apple.com/us/app/jumble-find-st...,1,1,ryderj,9/25/2016 20:06
...,...,...,...,...,...,...,...
292995,10177714,Show HN: Repartee The SMS Messaging Stack for...,https://github.com/markgreenall/Repartee,2,0,Nuratu,9/6/2015 14:21
293002,10177631,Show HN: Immutable and type-checked state and ...,https://github.com/gcanti/redux-tcomb,20,2,gcanti,9/6/2015 13:50
293019,10177511,Show HN: MockTheClock A tiny JavaScript libra...,https://github.com/zb3/MockTheClock,18,6,zb3,9/6/2015 13:02
293028,10177459,Show HN: AppyPaper Gift wrap with app icons p...,http://www.appypaper.com/,6,4,submitstartup,9/6/2015 12:38
293037,10177421,Show HN: Popularity scoring for arXiv publicat...,https://gist.github.com/nebw/5504697c118744677c2d,17,1,nebw,9/6/2015 12:16

In [11]:
other_posts

,id,title,url,num_points,num_comments,author,created_at
0,12579008,You have two days to comment if you want stem ...,http://www.regulations.gov/document?D=FDA-2015...,1,0,altstar,9/26/2016 3:26
1,12579005,SQLAR the SQLite Archiver,https://www.sqlite.org/sqlar/doc/trunk/README.md,1,0,blacksqr,9/26/2016 3:24
2,12578997,What if we just printed a flatscreen televisio...,https://medium.com/vanmoof/our-secrets-out-f21...,1,0,pavel_lishin,9/26/2016 3:19
3,12578989,algorithmic music,http://cacm.acm.org/magazines/2011/7/109891-al...,1,0,poindontcare,9/26/2016 3:16
4,12578979,How the Data Vault Enables the Next-Gen Data W...,https://www.talend.com/blog/2016/05/12/talend-...,1,0,markgainor1,9/26/2016 3:14
...,...,...,...,...,...,...,...
293113,10176923,Why we aren't tempted to use ACLs on our Unix ...,https://utcc.utoronto.ca/~cks/space/blog/sysad...,34,23,mjn,9/6/2015 6:03
293115,10176917,Attention and awareness in stage magic: turnin...,http://people.cs.uchicago.edu/~luitien/nrn2473...,14,0,stakent,9/6/2015 6:01
293116,10176908,Dying vets fuck you letter (2013),http://dangerousminds.net/comments/dying_vets_...,10,2,mycodebreaks,9/6/2015 5:56
293117,10176907,"PHP 7 Coolest Features: Space Ships, Type Hint...",https://www.zend.com/en/resources/php-7,2,0,Garbage,9/6/2015 5:55
293118,10176903,Toyota Establishes Research Centers with MIT a...,http://newsroom.toyota.co.jp/en/detail/9233109/,4,0,tim_sw,9/6/2015 5:50

In [12]:
ask_posts['num_comments'].mean()

np.float64(10.38591888050727)

In [14]:
show_posts['num_comments'].mean()

np.float64(4.909804691333791)

In [15]:
other_posts['num_comments'].mean()

np.float64(6.401198005437156)

In [17]:
other_posts['num_comments'].describe()

count    283972.000000
mean          6.401198
std          29.850138
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max        2531.000000
Name: num_comments, dtype: float64

In [18]:
show_posts['num_comments'].describe()

count    10189.000000
mean         4.909805
std         16.358716
min          0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max        306.000000
Name: num_comments, dtype: float64

In [19]:
ask_posts['num_comments'].describe()

count    9147.000000
mean       10.385919
std        43.489889
min         0.000000
25%         1.000000
50%         2.000000
75%         6.000000
max      1007.000000
Name: num_comments, dtype: float64